[project]
name="cellular_automata"
version="0.0.0"
edition="0.0.0"

[[todo]]
name="better drawing"
difficulty=0.1
priority=0.3


[[todo]]
name="better interaction"
difficulty=0.4
priority=0.7

[[todo.subfeature]]
name="impl Widget for Board"
difficulty=0.9
priority=0.7

[[todo.subfeature]]
name="run pause toggle cells"
difficulty=0.9
priority=0.7


[[todo]]
name="conways cell randomizer"
difficulty=0.3
priority=0.1


[[done]]
name="Conways Game of life"
difficulty=0.2
priority=0.3

[[done]]
name="Generic Automata Cell"
difficulty=0.8
priority=0.8
