[project]
name = "cellular_automata"
version = "0.0.0"
edition = "0.1.0"

[[todo]]
name = "Add more board types"
priority = 0.1
difficulty = 0.4

[[done]]
name = "Wrapped GOL"
priority = 0.1
difficulty = 0.1

[[done]]
name = "Basic Falling Water"
priority = 0.1
difficulty = 0.1
